#!/usr/bin/env python3
"""
Demo of enhanced retry system with platform awareness
Demonstrates how patched tool now provides better context during retries
"""

logo = r"""
██████╗  █████╗ ████████╗ ██████╗██╗  ██╗
██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██║  ██║
██████╔╝███████║   ██║   ██║     ███████║
██╔═══╝ ██╔══██║   ██║   ██║     ██╔══██║
██║     ██║  ██║   ██║   ╚██████╗██║  ██║
╚═╝     ╚═╝  ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝


> your broken command has been patched
"""
print(logo)

print()
print("=" * 60)
print("   Enhanced Retry System with Platform Awareness")
print("=" * 60)
print()

print("-" * 30, " BEFORE ", "-" * 30)
print()
print("User: sudo systemctl start docker")
print("Error: systemctl: command not found")
print()
print("AI receives minimal context:")
print("  'Fix this command error: systemctl: command not found'")
print()
print("AI suggests: brew services start docker (50% confidence)")
print()
print("User retries → SAME suggestion!")
print()
print("PROBLEM: AI has NO IDEA:")
print("  • User is on macOS (not Linux)")
print("  • `systemctl` doesn't exist on macOS")
print("  • Previous fix FAILED, needs DIFFERENT approach")
print("  • Same error repeats → same suggestion")
print()

print("-" * 30, " AFTER ", "-" * 30)
print()
print("User: sudo systemctl start docker")
print("Error: systemctl: command not found")
print()
print("AI receives enhanced context on retry:")
print("  PREVIOUS SUGGESTION THAT FAILED: brew services start docker")
print("  This fix DID NOT WORK and produced the SAME ERROR.")
print("  Command attempted: sudo systemctl start docker")
print("  Platform: macOS")
print("  Application: Docker")
print("  Error type: daemon_not_running: macOS app needs to be opened")
print("  Error: systemctl: command not found")
print()
print("  CRITICAL INSTRUCTION: You suggested a tool/command that does NOT")
print("  exist on this platform. Platform is macOS.")
print("  REQUIRE: Suggest a DIFFERENT approach using platform-appropriate tools.")
print("  Do NOT suggest: brew services start docker or similar")
print("  ")
print("  Platform-specific guidance:")
print("    - macOS: Use `open -a Docker` to open apps, `brew` for packages")
print()
print("  Error message: systemctl: command not found")
print("  Please suggest a DIFFERENT, platform-appropriate solution.")
print()
print("AI suggests: open -a Docker:::95:::Start Docker Desktop app")
print()

print("=" * 60)
print("   Key Improvements")
print("=" * 60)
print()
print("1. Explicit Failure Notification:")
print("   BEFORE: 'The previous fix still failed.' ")
print("   AFTER:  'PREVIOUS SUGGESTION THAT FAILED: ... DID NOT WORK' ")
print()
print("2. Platform-aware Instructions:")
print("   BEFORE: No platform information")
print("   AFTER: Full platform context + guidance (macOS vs Linux)")
print()
print("3. Clear Differentiation:")
print("   BEFORE: Same suggestion every retry")
print("   AFTER: 'REQUIRE: Suggest a DIFFERENT approach'")
print("           'Do NOT suggest X or similar Linux/Unix commands'")
print()
print("4. Tool Existence Checking:")
print("   BEFORE: AI doesn't know what tools exist")
print("   AFTER: 'You suggested a tool that does NOT exist on this platform'")
print()
print("5. Platform-Specific Guidance:")
print("   BEFORE: No guidance")
print("   AFTER: macOS → open -a, brew, launchctl")
print("           Linux  → systemctl, apt, yum, dnf")
print()

print("=" * 60)
print("   Example: Docker on macOS")
print("=" * 60)
print()
print("Command: sudo systemctl start docker")
print("Error: systemctl: command not found")
print()
print("Retry 1:")
print("  AI context: macOS, Docker, daemon_not_running")
print("  AI suggests: brew services start docker (WRONG - doesn't exist!)")
print()
print("Retry 2 (WITH NEW SYSTEM):")
print("  AI receives: PREVIOUS SUGGESTION THAT FAILED!")
print("  'Systemctl does not exist on macOS. See error message.'")
print("  'macOS: Use open -a to open Docker'")
print("  '")
print("  AI suggests: open -a Docker:::95:::Start Desktop app ")
print("                ✓ CORRECT!")
print()

print("=" * 60)
print("   Example: Package manager")
print("=" * 60)
print()
print("Command: sudo apt install python3")
print("Error: apt: command not found")
print()
print("AI context: macOS, apt, package manager not found")
print("  Suggests: brew install python3 or download script ✓")
print()

print("=" * 60)
print("   Example: Service not found on macOS")
print("=" * 60)
print()
print("Command: systemctl start nginx")
print("Error: systemctl: command not found")
print()
print("AI context: macOS, systemctl don't exist")
print("  Suggests: open -a Nginx or brew services start ✓")
print()

print("=" * 60)
print("   System Prompt Enhancements")
print("=" * 30)
print()
print("ADDED to system_prompt:")
print()
print("IMPORTANT CONTEXT RULES:")
print("  1. ALWAYS read the provided: Platform, Application, Error type")
print("  2. ALWAYS suggest PLATFORM-APPROPRIATE fixes:")
print("     - macOS: Use `open -a`, `launchctl`, `brew`")
print("     - Linux: Use `systemctl`, `service`, `apt`, `yum`, `dnf`")
print("     - DO NOT suggest macOS fixes for Linux or vice versa")
print("  3. Application-specific commands:")
print("     - Docker: macOS → `open -a Docker`, Linux → `systemctl start docker`")
print("  4. If retrying: CLEARLY state it did NOT work")
print()

print("=" * 60)
print("   Error Type Intelligence")
print("=" * 60)
print()
print("categorize_error_type() function detects:")
print()
print("  daemon_not_running -> 'macOS: open -a Docker' | 'Linux: systemctl start'")
print("  command_syntax    -> Fix invalid options/flags")
print("  permission_denied  -> Suggest sudo or fix permissions")
print("  file_not_found    -> Check file existence")
print("  network_error     -> Check DNS, network connectivity")
print("  dependency_missing-> Check package name")
print("  configuration     -> Check config files")
print()
print("→ Platform-specific suggestions passed to AI!")
print()

print("=" * 60)
print("   Retry Flow")
print("=" * 60)
print()
print("1. User: sudo systemctl start docker")
print("2. Error: systemctl not found")
print("3. AI suggests: brew services start docker (WRONG)")
print("4. User clicks [2] Retry")
print("5. System says: PREVIOUS SUGGESTION FAILED...")
print("6. AI sees: 'macOS' + 'systemctl doesn't exist'")
print("7. AI thinks: 'Use open -a Docker instead'")
print("8. AI suggests: open -a Docker (CORRECT!)")
print()

print("=" * 60)
print("   Testing")
print("=" * 60)
print()
print("Try these commands to see enhanced retry:")
print()
print("# macOS Docker")
print("python3 patch.py sudo systemctl start docker")
print()
print("# macOS package manager")
print("python3 patch.py sudo apt install python3")
print()
print("# Linux Docker")
print("python3 patch.py docker status")
# Add context note about the issue
print("")
print("[!] All suggestions now include platform information")
print("[!] Retries will be DIFFERENT each time (not repetitive)")
print("[!] System detects when suggest tool doesn't exist")
print("[!] Platform-specific guidance every time!")

print()
print("[!] Done!")